export const pageNames = {
  abTesting: "A/B Testing",
  addRemoveElements: "Add/Remove Elements",
  basicAuth: "Basic Auth",
  brokenImages: "Broken Images",
  challengingDom: "Challenging DOM",
  checkboxes: "Checkboxes",
  contextMenu: "Context Menu",
  digestAuth: "Digest Authentication (user and pass: admin)",
  disappearingElements: "Disappearing Elements",
  dragAndDrop: "Drag and Drop",
  dropdown: "Dropdown",
  dynamicContent: "Dynamic Content",
  dynamicControls: "Dynamic Controls",
  dynamicLoading: "Dynamic Loading",
  entryAd: "Entry Ad",
  exitIntent: "Exit Intent",
  fileDownload: "File Download",
  fileUpload: "File Upload",
  floatingMenu: "Floating Menu",
  forgotPassword: "Forgot Password",
  formAuth: "Form Authentication",
  frames: "Frames",
  geolocation: "Geolocation",
  horizontalSlider: "Horizontal Slider",
  hovers: "Hovers",
  infiniteScroll: "Infinite Scroll",
  inputs: "Inputs",
  jqueryUiMenus: "JQuery UI Menus",
  jsAlerts: "JavaScript Alerts",
  jsOnloadError: "JavaScript onload event error",
  keyPresses: "Key Presses",
  largeDeepDom: "Large & Deep DOM",
  multipleWindows: "Multiple Windows",
  nestedFrames: "Nested Frames",
  notificationMessages: "Notification Messages",
  redirectLink: "Redirect Link",
  secureFileDownload: "Secure File Download",
  shadowDom: "Shadow DOM",
  shiftingContent: "Shifting Content",
  slowResources: "Slow Resources",
  sortableDataTables: "Sortable Data Tables",
  statusCodes: "Status Codes",
  typos: "Typos",
  wysiwygEditor: "WYSIWYG Editor",
};
